version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
      - image: circleci/python:3.10
      - image: circleci/python:3.11
    resource_class: medium
    environment:
      CI: cicleci
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      SHELL: /bin/bash
    working_directory: ~/ymmv
    steps:
      - checkout
      - run:
          name: "fetch and pull"
          command: |
            git fetch && git pull --all || true
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/ymmv

  test:
    docker:
      - image: circleci/python:3.9
      - image: circleci/python:3.10
      - image: circleci/python:3.11
    parallelism: 2
    resource_class: medium
    environment:
      CI: cicleci
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      SHELL: /bin/bash
    working_directory: ~/ymmv
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          shell: /bin/bash
          name: "clean up for test"
          command: |
            make clean
          when: always
      - run:
          shell: /bin/bash
          name: "Unit Tests"
          command: |
            make test
          when: on_success
      - run:
          shell: /bin/bash
          name: "clean up from test"
          command: |
            make clean
          when: always
      - run:
          shell: /bin/bash
          name: "clean up from FAIL"
          command: |
            make clean
          when: on_fail

  lint:
    docker:
      - image: circleci/python:3.11
    resource_class: medium
    environment:
      CI: cicleci
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.UTF-8
      SHELL: /bin/bash
      LC_CTYPE: en_US.UTF-8
    working_directory: ~/ymmv
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "install flake8 attempt"
          command: |
            python3 -m pip install --user flake8 || true
      - run:
          shell: /bin/bash
          name: "clean up for test"
          command: |
            make clean
      - run:
          shell: /bin/bash
          name: "check code style and spelling"
          command: |
            make test-style || python3 -m flake8 --ignore=W191,W391,E117 --max-line-length=100 --verbose --count --config=.flake8.ini --max-complexity=10
      - run:
          shell: /bin/bash
          name: "clean up when done"
          command: |
            make clean

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
