---
version: 2.1
commands:
  cleanup:
    steps:
      - run:
          shell: /bin/bash
          name: "Cleanup"
          command: |
            make clean
          when: on_success
      - run:
          shell: /bin/bash
          name: "Cleanup (after Failure)"
          command: |
            make clean
          when: on_fail

jobs:
  build:
    docker:
      - image: cimg/base:current-24.04
    resource_class: medium
    environment:
      CI: cicleci
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      SHELL: /bin/bash
    working_directory: ~/ymmv
    steps:
      - checkout
      - run:
          name: "fetch and pull"
          command: |
            git fetch && git pull --all || true
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/ymmv

  test:
    docker:
      - image: cimg/base:current-24.04
    parallelism: 2
    resource_class: medium
    environment:
      CI: cicleci
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      SHELL: /bin/bash
    working_directory: ~/ymmv
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - cleanup
      - run:
          shell: /bin/bash
          name: "Unit Tests"
          command: |
            make test
          when: on_success
      - cleanup

  lint:
    docker:
      - image: cimg/python:3.13
    resource_class: medium
    environment:
      CI: cicleci
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.UTF-8
      SHELL: /bin/bash
      LC_CTYPE: en_US.UTF-8
    working_directory: ~/ymmv
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: "install flake8 attempt"
          command: |
            python3 -m pip install --upgrade --user flake8 || true
      - cleanup
      - run:
          shell: /bin/bash
          name: "check code style and spelling"
          command: |
            make test-style || python3 -m flake8 --ignore=W191,W391,E117 --max-line-length=100 --verbose --count --config=.flake8.ini --max-complexity=10
      - cleanup

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
