#! /bin/bash --posix

# version 20140517

umask 137

while [[ ($# -gt 1) && (${1:1:1} = '-') ]] ; do
GREP_ARGS="${GREP_ARGS} ${1}"
shift
done

/bin/grep ${GREP_ARGS} -oE "([12]?[0-9]?[0-9]{1}[\.]{1}){3}([12]?[0-9]?[0-9]{1}){1}" $@

exit 0 ;
